export const GenderOptions = ["Male", "Female"];

export const PatientFormDefaultValues = {
  // firstName: "",
  // lastName: "",
  // email: "",
  // phone: "",
  birthDate: new Date(Date.now()),
  gender: "Male" as Gender,
  address: "",
  occupation: "",
  emergancyContactName: "",
  emergancyConatctNumber: "",
  doctor: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "Birth Certificate",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};

export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Resident Alien Card (Green Card)",
  "Social Security Card",
  "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const Doctors: doctors[] = [
  {
    $id: "673a2976663362ff0a39",
    image: "/assets/images/dr-green.png",
    name: "John Green",
    specialization: "Cardiologist",
    experience: 12,
    charges: 500,
    bio: "Dr. John Green is a board-certified cardiologist with over 12 years of experience in managing and treating cardiovascular diseases. He specializes in minimally invasive heart procedures, hypertension management, and preventive cardiology. Dr. Green is known for his empathetic approach and his commitment to improving patient outcomes. He is passionate about educating patients on lifestyle modifications to promote heart health and prevent future complications.",
  },
  {
    $id: "673a2976ba0d8288667d",
    image: "/assets/images/dr-cameron.png",
    name: "Leila Cameron",
    specialization: "Dermatologist",
    experience: 8,
    charges: 300,
    bio: "Dr. Leila Cameron is an experienced dermatologist who has spent 8 years addressing various skin conditions, including acne, eczema, psoriasis, and skin cancer. She is also highly skilled in cosmetic dermatology, offering procedures such as laser therapy, chemical peels, and anti-aging treatments. Her dedication to personalized care ensures that each patient receives treatments tailored to their unique skin type and concerns.",
  },
  {
    $id: "673a297709f09f81b8c4",
    image: "/assets/images/dr-livingston.png",
    name: "David Livingston",
    specialization: "Pediatrician",
    experience: 15,
    charges: 400,
    bio: "With over 15 years of experience, Dr. David Livingston is a trusted pediatrician dedicated to providing comprehensive medical care for children from infancy to adolescence. He specializes in preventive health care, developmental assessments, and managing chronic conditions in young patients. Known for his approachable demeanor, Dr. Livingston builds strong relationships with families to ensure the best possible care for children.",
  },
  {
    $id: "673a29773c13ac291de5",
    image: "/assets/images/dr-peter.png",
    name: "Evan Peter",
    specialization: "Orthopedic Surgeon",
    experience: 10,
    charges: 700,
    bio: "Dr. Evan Peter is a highly skilled orthopedic surgeon with a decade of experience in treating musculoskeletal disorders and injuries. He specializes in joint replacement surgeries, sports injuries, and minimally invasive procedures. Dr. Peter's precision and attention to detail have earned him a reputation for delivering excellent patient outcomes and restoring mobility to countless individuals.",
  },
  {
    $id: "673a29776bfe57f7f0f9",
    image: "/assets/images/dr-powell.png",
    name: "Jane Powell",
    specialization: "Neurologist",
    experience: 20,
    charges: 1000,
    bio: "Dr. Jane Powell is a distinguished neurologist with 20 years of experience diagnosing and managing neurological disorders, including epilepsy, multiple sclerosis, and stroke recovery. Her expertise extends to advanced neuroimaging techniques and innovative treatment approaches. Dr. Powell is dedicated to improving patients' quality of life by combining evidence-based medicine with a compassionate, patient-centered approach.",
  },
  {
    $id: "673a29779ab7e9da640c",
    image: "/assets/images/dr-remirez.png",
    name: "Alex Ramirez",
    specialization: "Psychiatrist",
    experience: 5,
    charges: 250,
    bio: "Dr. Alex Ramirez is a compassionate psychiatrist with a focus on mental health treatment and holistic patient care. With 5 years of experience, he specializes in managing anxiety disorders, depression, and bipolar disorder. Dr. Ramirez combines traditional therapies with modern techniques, ensuring a supportive environment for his patients to achieve emotional well-being and resilience.",
  },
  {
    $id: "673a2977ca633624dbe3",
    image: "/assets/images/dr-lee.png",
    name: "Jasmine Lee",
    specialization: "Gynecologist",
    experience: 18,
    charges: 600,
    bio: "Dr. Jasmine Lee is a respected gynecologist with 18 years of experience in women's health care. She specializes in prenatal care, minimally invasive gynecological surgeries, and fertility treatments. Dr. Lee is deeply committed to empowering women through education and personalized care, ensuring her patients receive the highest quality treatment at every stage of life.",
  },
  {
    $id: "673a2978198baa63f3d7",
    image: "/assets/images/dr-cruz.png",
    name: "Alyana Cruz",
    specialization: "ENT Specialist",
    experience: 7,
    charges: 350,
    bio: "Dr. Alyana Cruz is an experienced ENT specialist who has been treating ear, nose, and throat conditions for over 7 years. Her expertise includes managing chronic sinusitis, hearing loss, and vocal cord disorders. Dr. Cruz is passionate about helping her patients regain their comfort and confidence by providing effective, personalized treatments for both common and complex ENT issues.",
  },
  {
    $id: "673a297848bf74ce2946",
    image: "/assets/images/dr-sharma.png",
    name: "Hardik Sharma",
    specialization: "General Physician",
    experience: 3,
    charges: 200,
    bio: "Dr. Hardik Sharma is a dedicated general physician with a focus on providing comprehensive primary care to his patients. With 3 years of experience, he excels in diagnosing and treating a wide range of medical conditions, from acute illnesses to chronic diseases. Dr. Sharma emphasizes preventive care and patient education to help his patients lead healthier lives.",
  },
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  cancelled: "/assets/icons/cancelled.svg",
};
